version: "3.9"
services:
  web:
    build:
      context: .
    container_name: crowd-server
    ports:
    - "3000:3000"
    volumes:
    - ./db:/app/db
    - ./experiments:/app/experiments
    - ./query_pages:/app/query_pages