version: "3.9"
services:
  crowd-frame-server:
    build:
      context: .
    image: crowd-frame-server
    container_name: crowd-frame-server
    ports:
    - "3000:3000"
    - "3010:3010"
    volumes:
    - ./db:/var/lib/postgresql/12/main
    - ./experiments.txt:/app/experiments.txt
    - ./query_pages:/app/query_pages